### ISSUE TITLE
Release app on Google Play Store

### ISSUE THREAD

**Issue by Kyle-Falconer** [Kyle-Falconer/AnimalSpin#7]
The app should be released on the Google Play Store for free.

Issues blocking this:
- [ ] Disabling TTS intros (issue #6)
- [x] App navigation fixed (issue #5)
- [x] add default TTS voice setting (issue #2)
